// TokenType.kt
// Version 1.0.2

package kconan.token

// Enum all possible types of token
enum class TokenType {
    IF_KEYWORD,
    ELSE_KEYWORD,
    WHILE_KEYWORD,
    FOR_KEYWORD,

    RETURN_KEYWORD,
    BREAK_KEYWORD,
    CONTINUE_KEYWORD,

    IMPORT_KEYWORD,
    AS_KEYWORD,

    THIS_KEYWORD,

    VAR_KEYWORD,
    FUN_KEYWORD,
    STRUCT_KEYWORD,

    I8_TYPE,
    U8_TYPE,
    I16_TYPE,
    U16_TYPE,
    I32_TYPE,
    U32_TYPE,
    I64_TYPE,
    U64_TYPE,
    F32_TYPE,
    F64_TYPE,
    CHAR_TYPE,
    BOOL_TYPE,

    TRUE_CONSTANT,
    FALSE_CONSTANT,
    NULL_CONSTANT,
    INTEGER_CONSTANT,
    FLOAT_CONSTANT,
    STRING_CONSTANT,
    CHAR_CONSTANT,

    LOGICAL_AND,
    LOGICAL_OR,
    LOGICAL_NOT,

    BITWISE_AND,
    BITWISE_OR,
    BITWISE_XOR,
    BITWISE_NOT,

    COMMA,
    PERIOD,
    SEMICOLON,
    COLON,
    OPENING_CURLY_BRACKET,
    CLOSING_CURLY_BRACKET,
    OPENING_PARENTHESIS,
    CLOSING_PARENTHESIS,
    OPENING_SQUARE_BRACKET,
    CLOSING_SQUARE_BRACKET,

    ASSIGN,

    ADDITION,
    SUBTRACTION,
    MULTIPLICATION,
    DIVISION,
    REMAINDER,

    EQUALS_TO,
    NOT_EQUALS_TO,
    GREATER_THAN,
    GREATER_OR_EQUALS,
    LESS_THAN,
    LESS_OR_EQUALS,

    INCREMENT,
    DECREMENT,
    ASSIGNMENT_BY_SUM,
    ASSIGNMENT_BY_DIFFERENCE,
    ASSIGNMENT_BY_PRODUCT,
    ASSIGNMENT_BY_QUOTIENT,
    ASSIGNMENT_BY_REMAINDER,

    IDENTIFIER
}