(*
kconan 1.0 doesn't support
    - classes
    - type inference
    - logical and, or, not
    - bitwise operators
*)

(*
Version 1.0.3
It doesn't support:
    - char variables
    - functions
    - parenthesis
*)

program = var_init;
program = program var_init;

var_init = VAR ?ID? COLON numeric_type ASSIGN exp;

numeric_type = U8 | I8 | U16 | I16 | U32 | I32 | U64 | I64 | F32 | F64;

exp = ?ID?;
exp = number;
exp = exp operator exp;

number = ?INT? | ?FLOAT?;

operator = ADDITION | SUBTRACTION | MULTIPLICATION | DIVISION;


VAR = "var";
COLON = ":";
ASSIGN = "=";
ADDITION = "+";
SUBTRACTION = "-";
MULTIPLICATION = "*";
DIVISION = "/";