(*
kconan 1.0 doesn't support
    - classes
    - type inference
    - logical and, or, not
    - bitwise operators
*)

(*
Version 1.0.14
It doesn't support:
    - char variables
    - parenthesis
*)

program = var_init | fun_declaration;
program = (var_init | fun_declaration) program;

var_init = VAR ?ID? COLON type ASSIGN exp;;

fun_declaration = FUN ?ID? OPEN_PARENTHESIS parameters CLOSE_PARENTHESIS COLON type OPEN_CURLY_BRACKET {statement} CLOSE_CURLY_BRACKET;

parameters = {parameter COMMA} parameter
parameters = ?EMPTY?

parameter = ?ID? COLON numeric_type

type = U8 | I8 | U16 | I16 | U32 | I32 | U64 | I64 | F32 | F64;

statement = var_assign;
statement = while;
statement = if

var_assign = ?ID? ASSIGN exp;;

while = WHILE "(" exp ")" "{" {statement} "}";
if = "if" "(" exp ")" "{" if_body "}" ["else" "{" else_body "}"];

if_body = {statement};
else_body = {statement};

// each rule from exp to primary also matches every rule of higher precedence
exp = c;
c = s {("==" | "!=" | ">" | ">=" | "<" | "<=") s};
s = p {("+" | "-") p};
p = primary {("*" | "/") primary};
primary = ?ID? | number | ("(" exp ")");

number = ?INT? | ?FLOAT?;

operator = ADDITION | SUBTRACTION | MULTIPLICATION | DIVISION;


VAR = "var";
COLON = ":";
ASSIGN = "=";
ADDITION = "+";
SUBTRACTION = "-";
MULTIPLICATION = "*";
DIVISION = "/";
FUN = "fun";
OPEN_CURLY_BRACKET = "{"
CLOSE_CURLY_BRACKET = "}"